-- ============================================================================
-- ICP ANGLES SYSTEM
-- Messaging angles per ICP for A/B testing and varied outreach approaches
-- ============================================================================

-- Create the icp_angles table
CREATE TABLE IF NOT EXISTS public.icp_angles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icp_profile_id BIGINT NOT NULL REFERENCES public.icp_profiles(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Core angle definition
    name TEXT NOT NULL,                         -- "Cost Savings Angle", "Speed Angle"
    description TEXT,                           -- What this angle focuses on
    value_proposition TEXT NOT NULL,            -- Core message/pitch
    
    -- Messaging elements
    pain_points TEXT[] DEFAULT '{}',            -- Pain points this angle addresses
    hooks TEXT[] DEFAULT '{}',                  -- Opening hooks for emails
    proof_points TEXT[] DEFAULT '{}',           -- Social proof/stats to use
    objection_handlers TEXT[] DEFAULT '{}',     -- Common objections and responses
    
    -- Tone and style
    tone TEXT DEFAULT 'professional' CHECK (tone IN ('professional', 'casual', 'urgent', 'consultative', 'challenger')),
    
    -- Status
    is_active BOOLEAN DEFAULT true,
    is_control BOOLEAN DEFAULT false,           -- Mark as control for A/B tests
    
    -- Performance tracking
    performance_stats JSONB DEFAULT '{
        "emails_sent": 0,
        "opens": 0,
        "replies": 0,
        "positive_replies": 0,
        "meetings_booked": 0,
        "open_rate": 0,
        "reply_rate": 0,
        "positive_rate": 0
    }'::jsonb,
    
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Add angle tracking to campaigns
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'outreach_campaigns' AND column_name = 'angle_id') THEN
        ALTER TABLE public.outreach_campaigns ADD COLUMN angle_id BIGINT REFERENCES public.icp_angles(id) ON DELETE SET NULL;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'outreach_campaigns' AND column_name = 'angle_ids') THEN
        ALTER TABLE public.outreach_campaigns ADD COLUMN angle_ids BIGINT[] DEFAULT '{}';
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'outreach_campaigns' AND column_name = 'ab_test_enabled') THEN
        ALTER TABLE public.outreach_campaigns ADD COLUMN ab_test_enabled BOOLEAN DEFAULT false;
    END IF;
END $$;

-- Add angle tracking to outreach queue for per-email tracking
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'outreach_queue' AND column_name = 'angle_id') THEN
        ALTER TABLE public.outreach_queue ADD COLUMN angle_id BIGINT REFERENCES public.icp_angles(id) ON DELETE SET NULL;
    END IF;
END $$;

-- Add angle tracking to sent_emails for performance analysis
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'sent_emails' AND column_name = 'angle_id') THEN
        ALTER TABLE public.sent_emails ADD COLUMN angle_id BIGINT REFERENCES public.icp_angles(id) ON DELETE SET NULL;
    END IF;
END $$;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_icp_angles_icp_profile_id ON public.icp_angles(icp_profile_id);
CREATE INDEX IF NOT EXISTS idx_icp_angles_user_id ON public.icp_angles(user_id);
CREATE INDEX IF NOT EXISTS idx_icp_angles_is_active ON public.icp_angles(is_active);
CREATE INDEX IF NOT EXISTS idx_outreach_campaigns_angle_id ON public.outreach_campaigns(angle_id);
CREATE INDEX IF NOT EXISTS idx_outreach_queue_angle_id ON public.outreach_queue(angle_id);

-- Enable RLS
ALTER TABLE public.icp_angles ENABLE ROW LEVEL SECURITY;

-- RLS Policies
DROP POLICY IF EXISTS "Users can view their own angles" ON public.icp_angles;
CREATE POLICY "Users can view their own angles" ON public.icp_angles
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create their own angles" ON public.icp_angles;
CREATE POLICY "Users can create their own angles" ON public.icp_angles
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own angles" ON public.icp_angles;
CREATE POLICY "Users can update their own angles" ON public.icp_angles
    FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own angles" ON public.icp_angles;
CREATE POLICY "Users can delete their own angles" ON public.icp_angles
    FOR DELETE USING (auth.uid() = user_id);

-- Function to update angle performance stats
CREATE OR REPLACE FUNCTION update_angle_performance(
    p_angle_id BIGINT,
    p_event_type TEXT  -- 'sent', 'opened', 'replied', 'positive_reply', 'meeting_booked'
)
RETURNS void AS $$
DECLARE
    v_stats JSONB;
    v_emails_sent INT;
    v_opens INT;
    v_replies INT;
    v_positive_replies INT;
    v_meetings INT;
BEGIN
    -- Get current stats
    SELECT performance_stats INTO v_stats
    FROM public.icp_angles
    WHERE id = p_angle_id;
    
    IF v_stats IS NULL THEN
        RETURN;
    END IF;
    
    -- Update the appropriate counter
    CASE p_event_type
        WHEN 'sent' THEN
            v_stats = jsonb_set(v_stats, '{emails_sent}', to_jsonb((v_stats->>'emails_sent')::int + 1));
        WHEN 'opened' THEN
            v_stats = jsonb_set(v_stats, '{opens}', to_jsonb((v_stats->>'opens')::int + 1));
        WHEN 'replied' THEN
            v_stats = jsonb_set(v_stats, '{replies}', to_jsonb((v_stats->>'replies')::int + 1));
        WHEN 'positive_reply' THEN
            v_stats = jsonb_set(v_stats, '{positive_replies}', to_jsonb((v_stats->>'positive_replies')::int + 1));
        WHEN 'meeting_booked' THEN
            v_stats = jsonb_set(v_stats, '{meetings_booked}', to_jsonb((v_stats->>'meetings_booked')::int + 1));
    END CASE;
    
    -- Recalculate rates
    v_emails_sent = (v_stats->>'emails_sent')::int;
    v_opens = (v_stats->>'opens')::int;
    v_replies = (v_stats->>'replies')::int;
    v_positive_replies = (v_stats->>'positive_replies')::int;
    
    IF v_emails_sent > 0 THEN
        v_stats = jsonb_set(v_stats, '{open_rate}', to_jsonb(ROUND((v_opens::numeric / v_emails_sent) * 100, 2)));
        v_stats = jsonb_set(v_stats, '{reply_rate}', to_jsonb(ROUND((v_replies::numeric / v_emails_sent) * 100, 2)));
    END IF;
    
    IF v_replies > 0 THEN
        v_stats = jsonb_set(v_stats, '{positive_rate}', to_jsonb(ROUND((v_positive_replies::numeric / v_replies) * 100, 2)));
    END IF;
    
    -- Update the record
    UPDATE public.icp_angles
    SET performance_stats = v_stats, updated_at = now()
    WHERE id = p_angle_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get angle count for an ICP (for plan limit enforcement)
CREATE OR REPLACE FUNCTION get_icp_angle_count(p_icp_profile_id BIGINT)
RETURNS INT AS $$
BEGIN
    RETURN (
        SELECT COUNT(*)::int
        FROM public.icp_angles
        WHERE icp_profile_id = p_icp_profile_id
        AND is_active = true
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to update updated_at
CREATE OR REPLACE FUNCTION update_icp_angles_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_icp_angles_updated_at ON public.icp_angles;
CREATE TRIGGER trigger_update_icp_angles_updated_at
    BEFORE UPDATE ON public.icp_angles
    FOR EACH ROW
    EXECUTE FUNCTION update_icp_angles_updated_at();

-- ============================================================================
-- SAMPLE DATA (Optional - for testing)
-- ============================================================================
-- Uncomment to add sample angles for testing:
/*
INSERT INTO public.icp_angles (icp_profile_id, user_id, name, description, value_proposition, pain_points, hooks, proof_points, tone)
SELECT 
    ip.id,
    ip.user_id,
    'Time Savings',
    'Focus on how much time prospects can save',
    'Stop wasting 20+ hours per week on manual prospecting. Our AI handles it in minutes.',
    ARRAY['Manual prospecting is time-consuming', 'SDRs spend too much time on admin'],
    ARRAY['What if you could get your prospecting done while you sleep?', 'Imagine never writing another cold email manually'],
    ARRAY['Customers save 25 hours/week on average', '3x more demos with same team size'],
    'professional'
FROM public.icp_profiles ip
LIMIT 1;
*/

COMMENT ON TABLE public.icp_angles IS 'Messaging angles for each ICP - different value propositions and approaches for A/B testing';
COMMENT ON COLUMN public.icp_angles.value_proposition IS 'The core message/pitch for this angle';
COMMENT ON COLUMN public.icp_angles.hooks IS 'Opening lines/hooks to use in emails with this angle';
COMMENT ON COLUMN public.icp_angles.is_control IS 'Mark as control variant for A/B tests';
