-- Safe Calendar Hosts Enhancement Migration
-- This version handles existing objects gracefully

-- Create calendar_hosts table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.calendar_hosts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    host_name TEXT NOT NULL,
    host_email TEXT NOT NULL,
    host_title TEXT,
    host_bio TEXT,
    host_avatar_url TEXT,
    grant_id TEXT NOT NULL,
    calendar_id TEXT,
    timezone TEXT NOT NULL DEFAULT 'UTC',
    working_hours JSONB DEFAULT '{"monday":{"start":"09:00","end":"17:00","enabled":true},"tuesday":{"start":"09:00","end":"17:00","enabled":true},"wednesday":{"start":"09:00","end":"17:00","enabled":true},"thursday":{"start":"09:00","end":"17:00","enabled":true},"friday":{"start":"09:00","end":"17:00","enabled":true},"saturday":{"start":"09:00","end":"17:00","enabled":false},"sunday":{"start":"09:00","end":"17:00","enabled":false}}'::jsonb,
    buffer_before_minutes INTEGER DEFAULT 0,
    buffer_after_minutes INTEGER DEFAULT 0,
    max_bookings_per_day INTEGER DEFAULT 8,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add calendar_host_id to booking_links table if it doesn't exist
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'booking_links' 
        AND column_name = 'calendar_host_id'
    ) THEN
        ALTER TABLE public.booking_links 
        ADD COLUMN calendar_host_id BIGINT REFERENCES public.calendar_hosts(id) ON DELETE SET NULL;
    END IF;
END $$;

-- Create indexes if they don't exist
CREATE INDEX IF NOT EXISTS idx_calendar_hosts_user_id ON public.calendar_hosts(user_id);
CREATE INDEX IF NOT EXISTS idx_calendar_hosts_grant_id ON public.calendar_hosts(grant_id);
CREATE INDEX IF NOT EXISTS idx_booking_links_calendar_host_id ON public.booking_links(calendar_host_id);

-- Enable RLS on calendar_hosts table
ALTER TABLE public.calendar_hosts ENABLE ROW LEVEL SECURITY;

-- Drop and recreate RLS policies to avoid conflicts
DROP POLICY IF EXISTS "Users can manage their own calendar hosts" ON public.calendar_hosts;
CREATE POLICY "Users can manage their own calendar hosts" ON public.calendar_hosts
    FOR ALL USING (auth.uid() = user_id);

-- Update booking_links RLS to include calendar_host_id access
DROP POLICY IF EXISTS "Users can manage their own booking links" ON public.booking_links;
CREATE POLICY "Users can manage their own booking links" ON public.booking_links
    FOR ALL USING (
        auth.uid() = user_id OR 
        EXISTS (
            SELECT 1 FROM public.calendar_hosts 
            WHERE calendar_hosts.id = booking_links.calendar_host_id 
            AND calendar_hosts.user_id = auth.uid()
        )
    );

-- Clean up function overloading conflicts
-- Drop all versions of get_available_slots to resolve overloading issues
DROP FUNCTION IF EXISTS get_available_slots(bigint, text, text);
DROP FUNCTION IF EXISTS get_available_slots(bigint, date, text);
DROP FUNCTION IF EXISTS get_available_slots(p_booking_link_id bigint, p_date text, p_timezone text);
DROP FUNCTION IF EXISTS get_available_slots(p_booking_link_id bigint, p_date date, p_timezone text);

-- Drop existing function if it exists (handles return type changes)
DROP FUNCTION IF EXISTS get_booking_link_with_host(TEXT);

-- Function to get booking link with host information
CREATE OR REPLACE FUNCTION get_booking_link_with_host(p_booking_slug TEXT)
RETURNS TABLE (
    -- Booking link fields
    id BIGINT,
    title TEXT,
    description TEXT,
    duration_minutes INTEGER,
    timezone TEXT,
    booking_slug TEXT,
    is_active BOOLEAN,
    meeting_location TEXT,
    meeting_type TEXT,
    grant_id TEXT,
    calendar_id TEXT,
    -- Host fields
    host_id BIGINT,
    host_name TEXT,
    host_email TEXT,
    host_title TEXT,
    host_bio TEXT,
    host_avatar_url TEXT,
    host_timezone TEXT,
    host_grant_id TEXT,
    host_calendar_id TEXT,
    host_working_hours JSONB,
    host_buffer_before INTEGER,
    host_buffer_after INTEGER,
    host_max_bookings INTEGER
) LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY
    SELECT 
        bl.id,
        bl.title,
        bl.description,
        bl.duration_minutes,
        bl.timezone,
        bl.booking_slug,
        bl.is_active,
        bl.meeting_location,
        bl.meeting_type,
        bl.grant_id,
        bl.calendar_id,
        -- Host fields (nullable if no host assigned)
        ch.id as host_id,
        ch.host_name,
        ch.host_email,
        ch.host_title,
        ch.host_bio,
        ch.host_avatar_url,
        ch.timezone as host_timezone,
        ch.grant_id as host_grant_id,
        ch.calendar_id as host_calendar_id,
        ch.working_hours as host_working_hours,
        ch.buffer_before_minutes as host_buffer_before,
        ch.buffer_after_minutes as host_buffer_after,
        ch.max_bookings_per_day as host_max_bookings
    FROM public.booking_links bl
    LEFT JOIN public.calendar_hosts ch ON bl.calendar_host_id = ch.id
    WHERE bl.booking_slug = p_booking_slug
    AND bl.is_active = true
    AND (ch.id IS NULL OR ch.is_active = true);
END;
$$;

-- Recreate get_available_slots function (SIMPLIFIED DEBUG VERSION)
CREATE OR REPLACE FUNCTION get_available_slots(
    p_booking_link_id BIGINT,
    p_date TEXT,
    p_timezone TEXT DEFAULT 'UTC'
)
RETURNS TABLE (
    start_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE,
    is_available BOOLEAN
) LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    booking_duration INTEGER;
    booking_working_hours JSONB;
    base_date DATE;
    day_name TEXT;
    day_config JSONB;
    work_start TIME := '09:00'::TIME;
    work_end TIME := '17:00'::TIME;
    day_enabled BOOLEAN := true;
    slot_start TIMESTAMP WITH TIME ZONE;
    slot_end TIMESTAMP WITH TIME ZONE;
    slot_time TIME;
BEGIN
    -- Get booking link configuration
    SELECT 
        COALESCE(duration_minutes, 30),
        working_hours
    INTO booking_duration, booking_working_hours
    FROM public.booking_links
    WHERE id = p_booking_link_id AND is_active = true;
    
    -- If no booking link found, return empty
    IF booking_duration IS NULL THEN
        RETURN;
    END IF;
    
    -- Parse the date and get day name (ensure consistent timezone handling)
    -- Parse date in UTC to avoid timezone shifts affecting day calculation
    base_date := (p_date || ' 12:00:00')::TIMESTAMP AT TIME ZONE 'UTC';
    day_name := LOWER(TO_CHAR(base_date, 'Day'));
    day_name := TRIM(BOTH ' ' FROM day_name); -- Explicitly trim spaces from both sides
    
    -- Try to get day configuration from working hours
    IF booking_working_hours IS NOT NULL THEN
        day_config := booking_working_hours -> day_name;
        
        -- If no configuration exists for this day, return empty (day not configured)
        IF day_config IS NULL THEN
            -- Day is not configured in working hours, return no slots
            RETURN;
        END IF;
        
        -- If enabled field exists, use it; otherwise default to true (day is enabled)
        day_enabled := COALESCE((day_config ->> 'enabled')::boolean, true);
        work_start := COALESCE((day_config ->> 'start')::TIME, '09:00'::TIME);
        work_end := COALESCE((day_config ->> 'end')::TIME, '17:00'::TIME);
    ELSE
        -- If no working hours configured, return empty
        RETURN;
    END IF;
    
    -- If day is disabled, return empty
    IF NOT day_enabled THEN
        RETURN;
    END IF;
    
    -- Generate slots every 30 minutes within working hours
    slot_time := work_start;
    
    WHILE slot_time < work_end LOOP
        -- Create slot timestamp in UTC, then convert to the requested timezone for display
        slot_start := (base_date + slot_time) AT TIME ZONE 'UTC';
        slot_end := slot_start + (booking_duration || ' minutes')::INTERVAL;
        
        -- Check if slot end time is within working hours
        IF slot_time + (booking_duration || ' minutes')::INTERVAL <= (work_end + INTERVAL '1 minute') THEN
            start_time := slot_start;
            end_time := slot_end;
            is_available := true;
            RETURN NEXT;
        END IF;
        
        -- Move to next 30-minute slot
        slot_time := slot_time + INTERVAL '30 minutes';
        
        -- Safety check to prevent infinite loop
        IF slot_time > '23:59'::TIME THEN
            EXIT;
        END IF;
    END LOOP;
    
    RETURN;
END;
$$;

-- Create trigger for updated_at timestamp on calendar_hosts
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Drop trigger if exists and create new one
DROP TRIGGER IF EXISTS update_calendar_hosts_updated_at ON public.calendar_hosts;
CREATE TRIGGER update_calendar_hosts_updated_at
    BEFORE UPDATE ON public.calendar_hosts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Migrate existing connected_inboxes as calendar_hosts (if any exist and no hosts exist yet)
DO $$
BEGIN
    -- Only migrate if calendar_hosts table is empty and connected_inboxes has data
    IF NOT EXISTS (SELECT 1 FROM public.calendar_hosts LIMIT 1) 
       AND EXISTS (SELECT 1 FROM public.connected_inboxes LIMIT 1) THEN
        
        INSERT INTO public.calendar_hosts (
            user_id,
            host_name,
            host_email,
            host_title,
            grant_id,
            timezone,
            is_active
        )
        SELECT DISTINCT
            ci.user_id,
            COALESCE(ci.email_address, ci.email_address) as host_name,
            ci.email_address as host_email,
            'Email Account' as host_title,
            ci.grant_id,
            'UTC' as timezone,
            ci.is_active
        FROM public.connected_inboxes ci
        WHERE ci.is_active = true
        ON CONFLICT DO NOTHING;
        
        -- Update existing booking_links to use the first available calendar host
        UPDATE public.booking_links 
        SET calendar_host_id = (
            SELECT ch.id 
            FROM public.calendar_hosts ch 
            WHERE ch.user_id = booking_links.user_id 
            LIMIT 1
        )
        WHERE calendar_host_id IS NULL
        AND EXISTS (
            SELECT 1 FROM public.calendar_hosts ch 
            WHERE ch.user_id = booking_links.user_id
        );
    END IF;
END $$;

-- Grant necessary permissions
GRANT ALL ON public.calendar_hosts TO authenticated;
GRANT ALL ON public.calendar_hosts TO service_role;
GRANT USAGE ON SEQUENCE calendar_hosts_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE calendar_hosts_id_seq TO service_role;

-- Debug function to test day name generation
CREATE OR REPLACE FUNCTION test_day_name(test_date TEXT)
RETURNS TABLE (
    input_date TEXT,
    parsed_date DATE,
    day_name TEXT,
    day_name_trimmed TEXT
) LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    base_date DATE;
    raw_day_name TEXT;
    trimmed_day_name TEXT;
BEGIN
    base_date := test_date::DATE;
    raw_day_name := LOWER(TO_CHAR(base_date, 'Day'));
    trimmed_day_name := TRIM(raw_day_name);
    
    input_date := test_date;
    parsed_date := base_date;
    day_name := raw_day_name;
    day_name_trimmed := trimmed_day_name;
    
    RETURN NEXT;
END;
$$;
