-- ============================================================================
-- CAMPAIGN A/B TESTING & AI OPTIMIZATION SYSTEM
-- Tracks performance, learns patterns, and enables AI-driven test strategies
-- ============================================================================

-- ============================================================================
-- 1. CAMPAIGN VARIANTS - Individual test variations
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.campaign_variants (
    id BIGSERIAL PRIMARY KEY,
    campaign_id UUID NOT NULL REFERENCES public.outreach_campaigns(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Variant identification
    variant_name TEXT NOT NULL, -- "Variant A", "Variant B", etc.
    variant_letter CHAR(1) NOT NULL, -- A, B, C, D, E
    
    -- What's being tested
    test_type TEXT NOT NULL CHECK (test_type IN ('lead_magnet', 'proof_point', 'subject_line', 'opening_line', 'multi_element')),
    
    -- Variant configuration (JSONB for flexibility)
    variant_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Example: {
    --   "lead_magnet": "ROI Calculator",
    --   "proof_point": "Case study: 300% increase",
    --   "subject_line_approach": "question_based",
    --   "opening_line_style": "pain_focused"
    -- }
    
    -- Email content (generated by AI)
    email_templates JSONB NOT NULL DEFAULT '[]'::jsonb,
    -- Array of email templates for each touch in sequence
    
    -- Lead assignment
    leads_assigned INTEGER DEFAULT 0,
    traffic_weight DECIMAL(5,2) DEFAULT 33.33, -- % of leads assigned to this variant
    
    -- Performance metrics
    emails_sent INTEGER DEFAULT 0,
    emails_delivered INTEGER DEFAULT 0,
    emails_opened INTEGER DEFAULT 0,
    emails_clicked INTEGER DEFAULT 0,
    emails_replied INTEGER DEFAULT 0,
    meetings_booked INTEGER DEFAULT 0,
    
    -- Calculated rates
    delivery_rate DECIMAL(5,2) DEFAULT 0,
    open_rate DECIMAL(5,2) DEFAULT 0,
    click_rate DECIMAL(5,2) DEFAULT 0,
    reply_rate DECIMAL(5,2) DEFAULT 0,
    meeting_rate DECIMAL(5,2) DEFAULT 0,
    
    -- Statistical analysis
    confidence_level DECIMAL(5,2), -- Statistical confidence vs other variants
    expected_performance DECIMAL(5,2), -- AI prediction before launch
    actual_performance DECIMAL(5,2), -- Actual reply rate
    
    -- Status
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'paused', 'winner', 'loser')),
    is_control BOOLEAN DEFAULT false, -- Is this the control/baseline variant?
    
    -- AI reasoning
    ai_reasoning TEXT, -- Why AI chose this variant configuration
    
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================================
-- 2. A/B TEST CONFIGURATIONS - Test setup and rules
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.ab_test_configs (
    id BIGSERIAL PRIMARY KEY,
    campaign_id UUID NOT NULL REFERENCES public.outreach_campaigns(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Test strategy
    test_strategy TEXT NOT NULL, -- "ai_recommended", "user_defined", "sequential"
    primary_test_type TEXT NOT NULL, -- What we're testing first
    
    -- Test parameters
    min_sample_size INTEGER DEFAULT 100, -- Minimum sends per variant
    confidence_threshold DECIMAL(5,2) DEFAULT 95.0, -- Required confidence to declare winner
    test_duration_days INTEGER DEFAULT 7,
    
    -- Traffic allocation
    split_method TEXT DEFAULT 'equal' CHECK (split_method IN ('equal', 'weighted', 'adaptive')),
    -- equal: 33/33/33, weighted: custom %, adaptive: AI adjusts based on performance
    
    -- Auto-optimization settings
    auto_optimize BOOLEAN DEFAULT true,
    auto_pause_losers BOOLEAN DEFAULT true,
    auto_generate_variants BOOLEAN DEFAULT true,
    pause_threshold DECIMAL(5,2) DEFAULT 50.0, -- Pause if performing X% worse than winner
    
    -- Multi-stage testing
    next_test_type TEXT, -- What to test after current winner is found
    testing_sequence JSONB DEFAULT '[]'::jsonb, -- Planned sequence of tests
    
    -- Status
    status TEXT DEFAULT 'running' CHECK (status IN ('running', 'completed', 'paused')),
    winner_variant_id BIGINT REFERENCES public.campaign_variants(id),
    
    -- AI decision tracking
    ai_recommendation JSONB, -- Full AI recommendation data
    user_override BOOLEAN DEFAULT false, -- Did user override AI recommendation?
    
    created_at TIMESTAMPTZ DEFAULT now(),
    completed_at TIMESTAMPTZ
);

-- ============================================================================
-- 3. CAMPAIGN PERFORMANCE HISTORY - Learning database
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.campaign_performance_history (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    campaign_id UUID REFERENCES public.outreach_campaigns(id) ON DELETE SET NULL,
    variant_id BIGINT REFERENCES public.campaign_variants(id) ON DELETE SET NULL,
    
    -- Campaign context
    objective TEXT NOT NULL,
    target_persona TEXT,
    icp_profile_id BIGINT REFERENCES public.icp_profiles(id) ON DELETE SET NULL,
    offer_id BIGINT REFERENCES public.offers(id) ON DELETE SET NULL,
    
    -- What was tested
    test_type TEXT NOT NULL,
    variant_elements JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- {
    --   "lead_magnet": "ROI Calculator",
    --   "proof_point": "Case study",
    --   "subject_line_approach": "question_based"
    -- }
    
    -- Performance results
    emails_sent INTEGER NOT NULL,
    open_rate DECIMAL(5,2),
    reply_rate DECIMAL(5,2),
    meeting_rate DECIMAL(5,2),
    
    -- Context factors (for AI learning)
    context_factors JSONB DEFAULT '{}'::jsonb,
    -- {
    --   "industries": ["SaaS", "Technology"],
    --   "company_size": "500-1000",
    --   "seniority": "C-Level",
    --   "region": "North America",
    --   "season": "Q1"
    -- }
    
    -- Outcome
    was_winner BOOLEAN DEFAULT false,
    performance_vs_baseline DECIMAL(5,2), -- % better/worse than baseline
    
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================================
-- 4. AI TEST STRATEGY DECISIONS - Track AI recommendations
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.ai_test_decisions (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    campaign_id UUID REFERENCES public.outreach_campaigns(id) ON DELETE CASCADE,
    
    -- AI recommendation
    recommended_test_type TEXT NOT NULL,
    reasoning TEXT NOT NULL,
    confidence_score DECIMAL(5,2) NOT NULL, -- AI's confidence in recommendation
    
    -- Supporting data
    historical_data_points INTEGER, -- How many past campaigns analyzed
    global_benchmark_data JSONB, -- Industry benchmarks used
    user_specific_patterns JSONB, -- Patterns found in user's history
    
    -- Predicted outcomes
    predicted_variants JSONB NOT NULL,
    -- [
    --   {
    --     "name": "Variant A",
    --     "config": {...},
    --     "expected_performance": 6.2,
    --     "reasoning": "..."
    --   }
    -- ]
    
    -- User action
    user_accepted BOOLEAN,
    user_modified BOOLEAN DEFAULT false,
    user_modifications JSONB,
    
    -- Actual outcome (filled in after test completes)
    actual_winner TEXT,
    actual_performance DECIMAL(5,2),
    prediction_accuracy DECIMAL(5,2), -- How close was AI's prediction?
    
    created_at TIMESTAMPTZ DEFAULT now(),
    outcome_recorded_at TIMESTAMPTZ
);

-- ============================================================================
-- 5. GLOBAL PERFORMANCE BENCHMARKS - Anonymized cross-user learning
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.global_performance_benchmarks (
    id BIGSERIAL PRIMARY KEY,
    
    -- Segment
    objective TEXT NOT NULL,
    persona_type TEXT, -- "C-Level", "VP", "Director", etc.
    industry TEXT,
    company_size_range TEXT,
    
    -- Test element
    test_type TEXT NOT NULL,
    element_type TEXT NOT NULL, -- "lead_magnet", "proof_point", etc.
    element_value TEXT NOT NULL, -- "ROI Calculator", "Case Study", etc.
    
    -- Aggregated performance (anonymized)
    total_campaigns INTEGER DEFAULT 0,
    total_sends INTEGER DEFAULT 0,
    avg_open_rate DECIMAL(5,2),
    avg_reply_rate DECIMAL(5,2),
    avg_meeting_rate DECIMAL(5,2),
    
    -- Statistical confidence
    sample_size INTEGER,
    confidence_interval DECIMAL(5,2),
    
    last_updated TIMESTAMPTZ DEFAULT now()
);

-- ============================================================================
-- INDEXES for performance
-- ============================================================================

-- Campaign variants
CREATE INDEX IF NOT EXISTS idx_campaign_variants_campaign ON public.campaign_variants(campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_variants_user ON public.campaign_variants(user_id);
CREATE INDEX IF NOT EXISTS idx_campaign_variants_status ON public.campaign_variants(status);

-- A/B test configs
CREATE INDEX IF NOT EXISTS idx_ab_test_configs_campaign ON public.ab_test_configs(campaign_id);
CREATE INDEX IF NOT EXISTS idx_ab_test_configs_user ON public.ab_test_configs(user_id);
CREATE INDEX IF NOT EXISTS idx_ab_test_configs_status ON public.ab_test_configs(status);

-- Performance history
CREATE INDEX IF NOT EXISTS idx_performance_history_user ON public.campaign_performance_history(user_id);
CREATE INDEX IF NOT EXISTS idx_performance_history_objective ON public.campaign_performance_history(objective);
CREATE INDEX IF NOT EXISTS idx_performance_history_test_type ON public.campaign_performance_history(test_type);
CREATE INDEX IF NOT EXISTS idx_performance_history_winner ON public.campaign_performance_history(was_winner);

-- AI decisions
CREATE INDEX IF NOT EXISTS idx_ai_decisions_user ON public.ai_test_decisions(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_decisions_campaign ON public.ai_test_decisions(campaign_id);
CREATE INDEX IF NOT EXISTS idx_ai_decisions_accepted ON public.ai_test_decisions(user_accepted);

-- Global benchmarks
CREATE INDEX IF NOT EXISTS idx_global_benchmarks_lookup ON public.global_performance_benchmarks(objective, test_type, element_type);

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE public.campaign_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ab_test_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_performance_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_test_decisions ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (for re-running migration)
DROP POLICY IF EXISTS "Users can view their own variants" ON public.campaign_variants;
DROP POLICY IF EXISTS "Users can insert their own variants" ON public.campaign_variants;
DROP POLICY IF EXISTS "Users can update their own variants" ON public.campaign_variants;
DROP POLICY IF EXISTS "Users can delete their own variants" ON public.campaign_variants;

DROP POLICY IF EXISTS "Users can view their own test configs" ON public.ab_test_configs;
DROP POLICY IF EXISTS "Users can insert their own test configs" ON public.ab_test_configs;
DROP POLICY IF EXISTS "Users can update their own test configs" ON public.ab_test_configs;

DROP POLICY IF EXISTS "Users can view their own performance history" ON public.campaign_performance_history;
DROP POLICY IF EXISTS "Users can insert their own performance history" ON public.campaign_performance_history;

DROP POLICY IF EXISTS "Users can view their own AI decisions" ON public.ai_test_decisions;
DROP POLICY IF EXISTS "Users can insert their own AI decisions" ON public.ai_test_decisions;
DROP POLICY IF EXISTS "Users can update their own AI decisions" ON public.ai_test_decisions;

DROP POLICY IF EXISTS "Authenticated users can view global benchmarks" ON public.global_performance_benchmarks;

-- Campaign variants policies
CREATE POLICY "Users can view their own variants" ON public.campaign_variants
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own variants" ON public.campaign_variants
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own variants" ON public.campaign_variants
    FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own variants" ON public.campaign_variants
    FOR DELETE USING (auth.uid() = user_id);

-- A/B test configs policies
CREATE POLICY "Users can view their own test configs" ON public.ab_test_configs
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own test configs" ON public.ab_test_configs
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own test configs" ON public.ab_test_configs
    FOR UPDATE USING (auth.uid() = user_id);

-- Performance history policies
CREATE POLICY "Users can view their own performance history" ON public.campaign_performance_history
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own performance history" ON public.campaign_performance_history
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- AI decisions policies
CREATE POLICY "Users can view their own AI decisions" ON public.ai_test_decisions
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own AI decisions" ON public.ai_test_decisions
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own AI decisions" ON public.ai_test_decisions
    FOR UPDATE USING (auth.uid() = user_id);

-- Global benchmarks are read-only for all authenticated users
CREATE POLICY "Authenticated users can view global benchmarks" ON public.global_performance_benchmarks
    FOR SELECT USING (auth.role() = 'authenticated');

-- ============================================================================
-- FUNCTIONS for automated updates
-- ============================================================================

-- Drop function if exists (for re-running migration)
DROP FUNCTION IF EXISTS update_variant_metrics() CASCADE;

-- Update variant metrics when performance changes
CREATE OR REPLACE FUNCTION update_variant_metrics()
RETURNS TRIGGER AS $$
BEGIN
    -- Calculate rates
    NEW.delivery_rate = CASE 
        WHEN NEW.emails_sent > 0 
        THEN ROUND((NEW.emails_delivered::DECIMAL / NEW.emails_sent) * 100, 2)
        ELSE 0 
    END;
    
    NEW.open_rate = CASE 
        WHEN NEW.emails_delivered > 0 
        THEN ROUND((NEW.emails_opened::DECIMAL / NEW.emails_delivered) * 100, 2)
        ELSE 0 
    END;
    
    NEW.click_rate = CASE 
        WHEN NEW.emails_opened > 0 
        THEN ROUND((NEW.emails_clicked::DECIMAL / NEW.emails_opened) * 100, 2)
        ELSE 0 
    END;
    
    NEW.reply_rate = CASE 
        WHEN NEW.emails_sent > 0 
        THEN ROUND((NEW.emails_replied::DECIMAL / NEW.emails_sent) * 100, 2)
        ELSE 0 
    END;
    
    NEW.meeting_rate = CASE 
        WHEN NEW.emails_replied > 0 
        THEN ROUND((NEW.meetings_booked::DECIMAL / NEW.emails_replied) * 100, 2)
        ELSE 0 
    END;
    
    NEW.actual_performance = NEW.reply_rate;
    NEW.updated_at = now();
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop trigger if exists (for re-running migration)
DROP TRIGGER IF EXISTS update_variant_metrics_trigger ON public.campaign_variants;

CREATE TRIGGER update_variant_metrics_trigger
    BEFORE UPDATE ON public.campaign_variants
    FOR EACH ROW
    EXECUTE FUNCTION update_variant_metrics();

-- ============================================================================
-- COMMENTS for documentation
-- ============================================================================

COMMENT ON TABLE public.campaign_variants IS 'Individual A/B test variants with performance tracking';
COMMENT ON TABLE public.ab_test_configs IS 'A/B test configuration and rules';
COMMENT ON TABLE public.campaign_performance_history IS 'Historical performance data for AI learning';
COMMENT ON TABLE public.ai_test_decisions IS 'Track AI test strategy recommendations and accuracy';
COMMENT ON TABLE public.global_performance_benchmarks IS 'Anonymized cross-user performance benchmarks';
