-- Create ICP (Ideal Customer Profile) system for Apollo-based lead discovery
-- This migration creates tables for managing ICP definitions and Apollo search criteria

-- Create ICP profiles table
CREATE TABLE public.icp_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    
    -- Apollo Search Criteria
    industries JSONB DEFAULT '[]'::jsonb, -- Array of industry names
    company_sizes JSONB DEFAULT '[]'::jsonb, -- Array of size ranges (e.g., "1-10", "11-50")
    locations JSONB DEFAULT '[]'::jsonb, -- Array of geographic locations
    technologies JSONB DEFAULT '[]'::jsonb, -- Array of technology keywords
    funding_stages JSONB DEFAULT '[]'::jsonb, -- Array of funding stages
    keywords JSONB DEFAULT '[]'::jsonb, -- Array of general keywords
    
    -- Job Title Criteria
    job_titles JSONB DEFAULT '[]'::jsonb, -- Array of target job titles
    seniority_levels JSONB DEFAULT '[]'::jsonb, -- Array of seniority levels
    departments JSONB DEFAULT '[]'::jsonb, -- Array of departments
    
    -- Additional Filters
    revenue_min BIGINT, -- Minimum annual revenue
    revenue_max BIGINT, -- Maximum annual revenue
    employee_count_min INTEGER, -- Minimum employee count
    employee_count_max INTEGER, -- Maximum employee count
    
    -- Apollo API Configuration
    apollo_filters JSONB DEFAULT '{}'::jsonb, -- Raw Apollo API filter object
    
    -- Usage Statistics
    usage_count INTEGER DEFAULT 0,
    last_used_at TIMESTAMPTZ,
    leads_discovered INTEGER DEFAULT 0,
    
    -- Status
    status TEXT CHECK (status IN ('active', 'draft', 'archived')) DEFAULT 'draft',
    
    CONSTRAINT icp_profiles_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create ICP discovery sessions table (tracks discovery runs)
CREATE TABLE public.icp_discovery_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    icp_profile_id BIGINT NOT NULL REFERENCES public.icp_profiles(id) ON DELETE CASCADE,
    
    -- Session Details
    session_name TEXT,
    apollo_query JSONB, -- The actual query sent to Apollo
    
    -- Results
    total_results INTEGER DEFAULT 0,
    leads_imported INTEGER DEFAULT 0,
    leads_enriched INTEGER DEFAULT 0,
    
    -- Status
    status TEXT CHECK (status IN ('running', 'completed', 'failed', 'cancelled')) DEFAULT 'running',
    error_message TEXT,
    
    -- Timing
    started_at TIMESTAMPTZ DEFAULT now(),
    completed_at TIMESTAMPTZ,
    
    CONSTRAINT icp_discovery_sessions_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_icp_profiles_user_id ON public.icp_profiles USING btree (user_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_icp_profiles_status ON public.icp_profiles USING btree (status) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_icp_profiles_last_used ON public.icp_profiles USING btree (last_used_at) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_icp_discovery_sessions_user_id ON public.icp_discovery_sessions USING btree (user_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_icp_discovery_sessions_icp_id ON public.icp_discovery_sessions USING btree (icp_profile_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_icp_discovery_sessions_status ON public.icp_discovery_sessions USING btree (status) TABLESPACE pg_default;

-- Enable Row Level Security (RLS)
ALTER TABLE public.icp_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.icp_discovery_sessions ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for ICP profiles
CREATE POLICY "Users can view their own ICP profiles" ON public.icp_profiles
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own ICP profiles" ON public.icp_profiles
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own ICP profiles" ON public.icp_profiles
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own ICP profiles" ON public.icp_profiles
    FOR DELETE USING (auth.uid() = user_id);

-- Create RLS policies for discovery sessions
CREATE POLICY "Users can view their own discovery sessions" ON public.icp_discovery_sessions
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own discovery sessions" ON public.icp_discovery_sessions
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own discovery sessions" ON public.icp_discovery_sessions
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own discovery sessions" ON public.icp_discovery_sessions
    FOR DELETE USING (auth.uid() = user_id);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_icp_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_icp_profiles_updated_at BEFORE UPDATE ON public.icp_profiles
    FOR EACH ROW EXECUTE FUNCTION update_icp_updated_at_column();

-- Insert sample ICP profiles for demonstration
INSERT INTO public.icp_profiles (
    user_id, name, description, industries, company_sizes, locations, 
    job_titles, seniority_levels, departments, employee_count_min, employee_count_max, status
) VALUES
(
    'f7ee9f97-dead-4f92-99de-23cd707e3f0c', 
    'SaaS Sales Directors', 
    'Mid-market SaaS companies with sales directors looking to scale outreach',
    '["Software", "SaaS", "Technology", "Cloud Computing"]',
    '["51-200", "201-500"]',
    '["United States", "Canada", "United Kingdom"]',
    '["Sales Director", "VP of Sales", "Head of Sales", "Sales Manager"]',
    '["Director", "VP", "Head", "Manager"]',
    '["Sales", "Revenue", "Business Development"]',
    50,
    500,
    'active'
),
(
    'f7ee9f97-dead-4f92-99de-23cd707e3f0c',
    'Enterprise Marketing Leaders',
    'Large enterprise companies with marketing leaders focused on lead generation',
    '["Enterprise Software", "Financial Services", "Healthcare", "Manufacturing"]',
    '["501-1000", "1001-5000", "5000+"]',
    '["United States", "Europe", "Australia"]',
    '["CMO", "VP of Marketing", "Head of Marketing", "Marketing Director"]',
    '["VP", "Head", "Director", "C-Level"]',
    '["Marketing", "Demand Generation", "Growth"]',
    200,
    10000,
    'active'
);

-- Add comments for documentation
COMMENT ON TABLE public.icp_profiles IS 'Stores Ideal Customer Profile definitions for Apollo-based lead discovery';
COMMENT ON TABLE public.icp_discovery_sessions IS 'Tracks Apollo discovery sessions and their results';
COMMENT ON COLUMN public.icp_profiles.apollo_filters IS 'Raw Apollo API filter object for advanced users';
COMMENT ON COLUMN public.icp_profiles.industries IS 'Array of target industry names for Apollo search';
COMMENT ON COLUMN public.icp_profiles.company_sizes IS 'Array of company size ranges (e.g., "1-10", "11-50")';
COMMENT ON COLUMN public.icp_profiles.job_titles IS 'Array of target job titles to search for';
