-- Create offers and personas tables for AISDR outreach system
-- This migration creates the core tables for managing offers and buyer personas

-- Create offers table
CREATE TABLE public.offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    value_proposition TEXT,
    pain_points JSONB DEFAULT '[]'::jsonb,
    benefits JSONB DEFAULT '[]'::jsonb,
    sales_assets JSONB DEFAULT '[]'::jsonb,
    usage_count INTEGER DEFAULT 0,
    conversion_rate DECIMAL(5,2) DEFAULT 0.00,
    status TEXT CHECK (status IN ('active', 'draft', 'archived')) DEFAULT 'draft',
    CONSTRAINT offers_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create personas table
CREATE TABLE public.personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    title_patterns JSONB DEFAULT '[]'::jsonb,
    company_size TEXT,
    industries JSONB DEFAULT '[]'::jsonb,
    pain_points JSONB DEFAULT '[]'::jsonb,
    messaging_hooks JSONB DEFAULT '[]'::jsonb,
    tone TEXT DEFAULT 'professional',
    usage_count INTEGER DEFAULT 0,
    conversion_rate DECIMAL(5,2) DEFAULT 0.00,
    status TEXT CHECK (status IN ('active', 'draft', 'archived')) DEFAULT 'draft',
    CONSTRAINT personas_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_offers_user_id ON public.offers USING btree (user_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_offers_status ON public.offers USING btree (status) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_offers_usage_count ON public.offers USING btree (usage_count) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_personas_user_id ON public.personas USING btree (user_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_personas_status ON public.personas USING btree (status) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_personas_usage_count ON public.personas USING btree (usage_count) TABLESPACE pg_default;

-- Enable Row Level Security (RLS)
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.personas ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for offers
CREATE POLICY "Users can view their own offers" ON public.offers
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own offers" ON public.offers
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own offers" ON public.offers
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own offers" ON public.offers
    FOR DELETE USING (auth.uid() = user_id);

-- Create RLS policies for personas
CREATE POLICY "Users can view their own personas" ON public.personas
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own personas" ON public.personas
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own personas" ON public.personas
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own personas" ON public.personas
    FOR DELETE USING (auth.uid() = user_id);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers to automatically update updated_at
CREATE TRIGGER update_offers_updated_at BEFORE UPDATE ON public.offers
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_personas_updated_at BEFORE UPDATE ON public.personas
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insert sample offers for demonstration
INSERT INTO public.offers (user_id, title, description, value_proposition, pain_points, benefits, sales_assets, status) VALUES
('f7ee9f97-dead-4f92-99de-23cd707e3f0c', 'AI Sales Automation Platform', 'Complete AI-powered sales automation solution for B2B companies', 'Increase sales efficiency by 300% while reducing manual outreach time by 90%', 
 '["Manual prospecting takes too much time", "Low response rates from cold outreach", "Difficulty scaling sales team", "Inconsistent messaging across team"]',
 '["Automated lead enrichment", "AI-powered personalization", "Smart follow-up sequences", "Real-time analytics and reporting"]',
 '["Product demo video", "ROI calculator", "Case study: TechCorp 300% increase", "Free trial access"]',
 'active'),
('f7ee9f97-dead-4f92-99de-23cd707e3f0c', 'Custom CRM Integration', 'Seamless integration with existing CRM systems', 'Eliminate data silos and streamline your sales process with our CRM integration', 
 '["Data scattered across multiple systems", "Manual data entry errors", "Poor visibility into sales pipeline", "Time wasted switching between tools"]',
 '["Single source of truth for customer data", "Automated data sync", "Enhanced pipeline visibility", "Reduced manual work"]',
 '["Integration guide", "Technical documentation", "Setup consultation call", "Success stories"]',
 'active');

-- Insert sample personas for demonstration
INSERT INTO public.personas (user_id, name, title_patterns, company_size, industries, pain_points, messaging_hooks, tone, status) VALUES
('f7ee9f97-dead-4f92-99de-23cd707e3f0c', 'Sales Director - Mid Market', 
 '["Sales Director", "VP of Sales", "Head of Sales", "Sales Manager"]',
 '50-200 employees',
 '["SaaS", "Technology", "Professional Services", "Manufacturing"]',
 '["Team struggling to hit quotas", "Manual processes slowing down sales", "Need better sales analytics", "Difficulty scaling outreach"]',
 '["Proven to increase quota attainment by 40%", "Automate your most time-consuming tasks", "Get real-time insights into your pipeline", "Scale your outreach without scaling headcount"]',
 'professional',
 'active'),
('f7ee9f97-dead-4f92-99de-23cd707e3f0c', 'Marketing Leader - Enterprise', 
 '["CMO", "VP of Marketing", "Head of Marketing", "Marketing Director"]',
 '200+ employees',
 '["Enterprise Software", "Financial Services", "Healthcare", "E-commerce"]',
 '["Lead quality is inconsistent", "Sales and marketing misalignment", "Attribution tracking challenges", "Need better lead scoring"]',
 '["Improve lead quality by 60%", "Align sales and marketing with shared data", "Track attribution across the entire funnel", "AI-powered lead scoring"]',
 'strategic',
 'active');

-- Add comments for documentation
COMMENT ON TABLE public.offers IS 'Stores offer templates for outreach campaigns';
COMMENT ON TABLE public.personas IS 'Stores buyer persona definitions for targeted messaging';
COMMENT ON COLUMN public.offers.pain_points IS 'Array of pain points this offer addresses';
COMMENT ON COLUMN public.offers.benefits IS 'Array of key benefits and value propositions';
COMMENT ON COLUMN public.offers.sales_assets IS 'Array of supporting sales materials and resources';
COMMENT ON COLUMN public.personas.title_patterns IS 'Array of job title patterns this persona matches';
COMMENT ON COLUMN public.personas.industries IS 'Array of target industries for this persona';
COMMENT ON COLUMN public.personas.messaging_hooks IS 'Array of proven messaging hooks for this persona';
