-- Create the replies table to store AI analysis of incoming emails
CREATE TABLE public.replies (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  -- This will link the reply to the user who owns the inbox
  user_id uuid references auth.users(id) on delete cascade not null,
  -- The grant_id from Nylas for which this reply was received
  grant_id text not null,
  -- The unique ID of the message from Nylas
  nylas_message_id text not null,
  -- Fields to be populated by the CrewAI agent
  sentiment text,
  action_required text, -- e.g., 'Needs Reply', 'No Action Needed', 'Urgent'
  summary text,
  -- The raw email address of the sender
  sender_email text
);

-- Add a comment for clarity
COMMENT ON COLUMN public.replies.user_id IS 'Links to the user who owns the inbox.';
COMMENT ON COLUMN public.replies.action_required IS 'Suggested next action, e.g., Needs Reply, No Action Needed.';

-- Enable Row Level Security
ALTER TABLE public.replies ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own replies." 
ON public.replies FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Service roles can insert replies." 
ON public.replies FOR INSERT
WITH CHECK (true); -- Webhook will use service_role key, so we allow inserts
