-- Create companies table for organization data (separate from leads)
-- This allows multiple leads to share the same company data and reduces API costs

CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Primary lookup key
    domain TEXT NOT NULL,
    
    -- Basic company info
    name TEXT,
    description TEXT,
    
    -- Industry classification
    industry TEXT,
    industries TEXT[] DEFAULT '{}',
    
    -- Company size & financials
    estimated_num_employees INTEGER,
    annual_revenue BIGINT,
    annual_revenue_printed TEXT,
    founded_year INTEGER,
    
    -- Keywords and technologies
    keywords TEXT[] DEFAULT '{}',
    technologies TEXT[] DEFAULT '{}',
    
    -- Social links
    website_url TEXT,
    linkedin_url TEXT,
    twitter_url TEXT,
    facebook_url TEXT,
    
    -- Contact & location
    phone TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    
    -- Branding
    logo_url TEXT,
    
    -- Full enrichment data (raw response for reference)
    enriched_data JSONB DEFAULT '{}',
    
    -- Enrichment status tracking
    enrichment_status TEXT DEFAULT 'pending' CHECK (enrichment_status IN ('pending', 'enriching', 'enriched', 'failed')),
    enrichment_source TEXT,  -- 'apollo', 'serper', etc.
    enriched_at TIMESTAMPTZ,
    
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Unique constraint: one company per domain per user
    UNIQUE(user_id, domain)
);

-- Add company_id foreign key to leads table
ALTER TABLE public.leads 
ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES public.companies(id) ON DELETE SET NULL;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_companies_user_id ON public.companies(user_id);
CREATE INDEX IF NOT EXISTS idx_companies_domain ON public.companies(domain);
CREATE INDEX IF NOT EXISTS idx_leads_company_id ON public.leads(company_id);

-- Enable RLS
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;

-- RLS Policies for companies table
CREATE POLICY "Users can view their own companies"
    ON public.companies FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own companies"
    ON public.companies FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own companies"
    ON public.companies FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own companies"
    ON public.companies FOR DELETE
    USING (auth.uid() = user_id);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_companies_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
DROP TRIGGER IF EXISTS trigger_companies_updated_at ON public.companies;
CREATE TRIGGER trigger_companies_updated_at
    BEFORE UPDATE ON public.companies
    FOR EACH ROW
    EXECUTE FUNCTION update_companies_updated_at();

-- Helper function to extract domain from email
CREATE OR REPLACE FUNCTION extract_domain_from_email(email TEXT)
RETURNS TEXT AS $$
BEGIN
    RETURN LOWER(SPLIT_PART(email, '@', 2));
END;
$$ LANGUAGE plpgsql IMMUTABLE;

COMMENT ON TABLE public.companies IS 'Stores enriched company/organization data, linked to leads via company_id';
COMMENT ON COLUMN public.companies.domain IS 'Primary lookup key - the company domain (e.g., transparity.com)';
COMMENT ON COLUMN public.companies.enriched_data IS 'Full raw enrichment response from Apollo/Serper for reference';
